### ISSUE TITLE
SCNMatrix4 init issue

### ISSUE THREAD

**Issue by farrukhaskari1** [laanlabs/ARBrush#1]
Cannot invoke 'SCNMatrix4.Type.init' with an argument list of type '(matrix_float4x4)'

any fix ?

**Comment by laanlabs** [comment]
Are you using xcode beta 2 ? The swift apis have change slightly.

**Comment by farrukhaskari1** [comment]
Xxode beta 1

**Comment by laanlabs** [comment]
Try upgrading and see if you still get the error.

**Comment by profjared** [comment]
Beta 2 fixes it, I had this same issue

**Comment by farrukhaskari1** [comment]
yes upgrading solved the problem
