### ISSUE TITLE
Crashes on bgra10_XR_sRGB

### ISSUE THREAD

**Issue by petard** [laanlabs/ARBrush#2]
The app crashes on view touch unless I change the pixelFormat in `VertBrush.swift` to ```pipelineStateDescriptor.colorAttachments[0].pixelFormat = MTLPixelFormat.bgra8Unorm_srgb```

I'm on a iPhone 7, is this expected?

**Comment by laanlabs** [comment]
It was hardcoded for my device. I'm sure there's a proper way to get the right format for the device; I have not looked into that yet though.
