### ISSUE TITLE
Crash on  renderEncoder.setRenderPipelineState(pipelineState)

### ISSUE THREAD

**Issue by ADevelopStudio** [laanlabs/ARBrush#3]
Crash on touch iPhone 7+ iOS11
<img width="1148" alt="screen shot 2017-06-29 at 9 28 59 am" src="https://user-images.githubusercontent.com/5238454/27664909-701d38ec-5cad-11e7-992f-4f2b17e2504d.png">

**Comment by laanlabs** [comment]
Should be fixed now

**Comment by ADevelopStudio** [comment]
Thanks! All's good now
