### ISSUE TITLE
I cannot run the code successfully .

### ISSUE THREAD

**Issue by noujan** [laanlabs/ARBrush#8]
I am trying to run the code on Xcode 10.1, iOS 11 and Swift 4. However, I am getting two errors in shaders.metal line 104 and 109:
line 104: no matching function for call to 'dot'
line 109: no matching function for call to 'reflect' 
does anyone solve the same issue?
Please let me know if you have any idea how to solve them. thank you

**Comment by willperkins** [comment]
please re-open this issue if you're still not able to run
